# 建立一个叫做CI的工作流
name: CI

#监听 master上的push事件
on:
  push:
    branches: [ master ]

# 开始任务
jobs:
  # 建立一个名为 build 的job
  build:
   runs-on: ubuntu-latest

   # 开始设置构建步骤
   steps:
   # 这是github官方action,用于clone该仓库的源码到工作流
   - uses: actions/checkout@v2
   - name: Build
     uses: actions/setup-node@v3
     with:
      node-version: "16.x"
   - run: npm install
   - run: npm run docs:build
     

   # 命令这个任务发布Deploy
  # - name: Deploy
  # 构建之后，把代码上传到服务器上,所以需要连接到ssh,并且做一个拷贝操作
# 上传打包资源
   - name: Deploy
     uses: easingthemes/ssh-deploy@v2.1.1
     env:
      SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ARGS: "-avzr --delete"
      SOURCE: './docs/.vuepress/dist/'
      REMOTE_HOST: ${{ secrets.TG_HOST }}
      REMOTE_USER: 'root'
      TARGET: '/home/vuepress' # 服务器目标路径
      EXCLUDE: "/node_modules/"
